### ISSUE TITLE
letter occurence

### ISSUE THREAD

**Issue by fragakis** [bellerb/wordle_solver#1]
Hi Ben,

I stumbled onto your project when trying to do wordle (just the game, no ai involved) for myself with my limited (and not pythonic in any way) coding skills.
The issue I'm raising is when you have the same letter occurring twice in a word you have guessed.
I was browsing for a solution to the problem when I came across your code.

Let's say the correct word is 'ready' and your guess is 'verse' the output would be 'Y'  'G' 'B' 'B' 'Y'.
So, that last 'Y' for the second e should be a 'B', as there are not two e's in 'ready'.

There should be some universal way of checking if a letter occurs twice (or more) either in the word or in the guess.

**Comment by bellerb** [comment]
Good catch, I think I can fix this using a hash table to count occurrence of letters in the word.

**Comment by bellerb** [comment]
This should be fixed now

**Comment by fragakis** [comment]
I'm sorry to be a pain but there's more to it than we thought.

Let's assume the word is S N A I L and the userinput is L E V E L.
The expected outcome would be 'B' 'B' 'B' 'B' 'G', but instead we get 'Y' 'B' 'B' 'B' 'G'.

In **_update_board_** the **_if self.word[i] == s:_** gets passed by in the first iteration.

**Comment by bellerb** [comment]
Good catch I'll re-open this issue till I get this fixed.

**Comment by bellerb** [comment]
I think I fixed this now. I had to take a bit of a different approach where I compare a hash table for the word and a hash table for the player's guess. Let me know if you're finding this problem still. If not I'll close this issue.

**Comment by fragakis** [comment]
word=HELLO
input=LEVEL
outcome=YGBBB instead of YGBBY

Maybe we should just skip all double letter words all together... 😄

**Comment by bellerb** [comment]
Sorry that was a dumb bug on my part I had a similar problem with green letters and just didn't add it to the yellow letters.
