### ISSUE TITLE
Error in Game Assist

### ISSUE THREAD

**Issue by wabee** [bellerb/wordle_solver#2]
Have tried out your interesting code and adapted it to Swedish. Getting the following error when trying 'Game Assist' mode:

GAME ASSIST ACTIVATED
---------------------
Traceback (most recent call last):
  File "/Users/Bengt/wordle_solver-main/main.py", line 65, in <module>
    game = Wordle(
  File "/Users/Bengt/wordle_solver-main/wordle.py", line 8, in __init__
    for l in word:
TypeError: 'NoneType' object is not iterable

**Comment by bellerb** [comment]
Sorry about that I broke that feature accidentally when I added in the yellow letter hash table. I fixed this though so it should be working now.

**Comment by wabee** [comment]
Still problems in 'Assist'. Tried it out on a problem and got the following results and run time error:

GAME ASSIST ACTIVATED
---------------------

Suggested Word = SEPIA

What were the colours returned [ex. ybggy]?
bybbb

Suggested Word = OÄDEL

What were the colours returned [ex. ybggy]?
bbbgb

Suggested Word = RUTER

What were the colours returned [ex. ybggy]?
bbbgb

Suggested Word = HÅKEN

What were the colours returned [ex. ybggy]?
bgbgg
Traceback (most recent call last):
  File "/Users/Bengt/wordle_solver-main/main.py", line 72, in <module>
    guess = bot.choose_action()
  File "/Users/Bengt/wordle_solver-main/bot.py", line 69, in choose_action
    result = random.choice(mv_bank['words'].tolist())
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/random.py", line 346, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

Word to solve was "VÅGEN"

**Comment by bellerb** [comment]
The problem seems to be with the filtering since your mv_bank size is 0. What word back are you using for Swedish so I can try and recreate the problem. I haven't been getting this problem in English when I test it. Do you also get this error when running a test for multiple games?

**Comment by wabee** [comment]
Hello

Checked further and it seems the word was not in the dictionary only the base form which is “våg”. 
I figured out the right answer manually. 
The tests work out flawlessly. 
Just close the issue. 
Thanks for looking into it, I should have done my homework better before bothering you!

Cheers,
