### ISSUE TITLE
Word bank length

### ISSUE THREAD

**Issue by khanna7** [bellerb/wordle_solver#7]
The medium page states that there are 15917 words

> Our word bank starts with 15917 words giving us an initial probability of only 0.0063%

but the `data/words.csv` file has 2311. Is the medium page out of date?

**Comment by bellerb** [comment]
Sorry yes I believe the medium article is out of date here. If you check the commit logs you'll notice I changed the word bank when the New York Times bought wordle to match their word bank. The app should still work as described however just on a different search space.
